"""init

Revision ID: f5194a9809ae
Revises: 
Create Date: 2026-09-04 22:32:54.727787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5194a9809ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_change_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('portal_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('acted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portal_change_logs_acted_at'), 'portal_change_logs', ['acted_at'], unique=False)
    op.create_index(op.f('ix_portal_change_logs_portal_id'), 'portal_change_logs', ['portal_id'], unique=False)
    op.create_table('portals',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('world_destination', sa.String(length=255), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('count_observers', sa.Integer(), nullable=False),
    sa.Column('marked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portals')
    op.drop_index(op.f('ix_portal_change_logs_portal_id'), table_name='portal_change_logs')
    op.drop_index(op.f('ix_portal_change_logs_acted_at'), table_name='portal_change_logs')
    op.drop_table('portal_change_logs')
    # ### end Alembic commands ###
